services:
  - type: web
    name: apollo-mcp-server
    runtime: docker
    repo: https://github.com/apollographql/mcp-server-template
    plan: free
    envVars:
      - key: APOLLO_GRAPH_REF
        sync: false
      - key: APOLLO_KEY
        sync: false
      - key: PORT
        value: "4000"
        sync: true
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    rootDir: ./
version: "1"
